import React, { useState } from "react";
import {
  ShieldCheck,
  ShieldAlert,
  AlertCircle,
  HelpCircle,
  Sparkles,
  ExternalLink,
  X,
  FileText,
  Calendar,
  Layers,
  Info,
  BookOpen,
  AlertTriangle,
} from "lucide-react";
import {
  CurriculumVerificationStatus,
  CurriculumSourceProvenance,
  CurriculumSourceConflict,
} from "../types";

export type StudentCurriculumStatusType =
  | "VERIFIED"
  | "OFFICIAL_RESOURCE_CONFIRMED"
  | "CURRICULUM_CONTENT_SUPPORTED"
  | "SOURCE_REQUIRED"
  | "APPLICATION_DERIVED";

interface CurriculumStatusBadgeProps {
  status?: CurriculumVerificationStatus | StudentCurriculumStatusType | string;
  provenance?: CurriculumSourceProvenance;
  academicYear?: string;
  sessionYear?: string;
  examYear?: number | string;
  sourceNote?: string;
  subjectCode?: string;
  conflicts?: CurriculumSourceConflict[];
  variant?: "badge" | "compact" | "banner" | "pill";
  showInspectButton?: boolean;
  className?: string;
}

/**
 * Standardized status presentation helper for Garia OS student experience.
 * Resolves the 5 user-facing intelligence states:
 * 1. VERIFIED: "Verified from official BSEB/SCERT source"
 * 2. OFFICIAL RESOURCE CONFIRMED: "Official source found; current-year applicability pending"
 * 3. CURRICULUM CONTENT SUPPORTED: "Supported by official curriculum material; current-year verification pending"
 * 4. SOURCE-REQUIRED: "Official 2026–27 confirmation required"
 * 5. APPLICATION-DERIVED: "Generated by Garia OS from available academic signals"
 */
export function resolveStudentCurriculumState(params: {
  status?: string;
  provenance?: CurriculumSourceProvenance;
  academicYear?: string;
}): {
  type: StudentCurriculumStatusType;
  label: string;
  shortLabel: string;
  studentExplanation: string;
  colorClass: string;
  borderClass: string;
  bgClass: string;
  textClass: string;
} {
  const rawStatus = (params.status || "SOURCE-REQUIRED").toUpperCase();
  const prov = params.provenance;
  const targetYear = params.academicYear || prov?.academicYear || "2026-27";

  if (rawStatus === "APPLICATION-DERIVED" || rawStatus === "APPLICATION_DERIVED") {
    return {
      type: "APPLICATION_DERIVED",
      label: "APPLICATION-DERIVED",
      shortLabel: "App-Derived",
      studentExplanation:
        "Generated by Garia OS from available academic signals, study weighting, and student progress; not an official board designation.",
      colorClass: "purple",
      borderClass: "border-purple-500/30",
      bgClass: "bg-purple-500/15",
      textClass: "text-purple-300",
    };
  }

  if (
    rawStatus === "VERIFIED" ||
    (prov?.verificationStatus === "VERIFIED" && prov?.currentYearApplicabilityProven)
  ) {
    return {
      type: "VERIFIED",
      label: "VERIFIED",
      shortLabel: "Verified",
      studentExplanation: "Verified from official BSEB/SCERT source.",
      colorClass: "emerald",
      borderClass: "border-emerald-500/30",
      bgClass: "bg-emerald-500/15",
      textClass: "text-emerald-300",
    };
  }

  if (
    prov?.curriculumContentSupported ||
    prov?.evidenceStage === "CURRICULUM_CONTENT_SUPPORTED" ||
    rawStatus === "CURRICULUM_CONTENT_SUPPORTED"
  ) {
    return {
      type: "CURRICULUM_CONTENT_SUPPORTED",
      label: "CURRICULUM CONTENT SUPPORTED",
      shortLabel: "Content Supported",
      studentExplanation: `Supported by official curriculum material; current ${targetYear} verification pending official circular.`,
      colorClass: "cyan",
      borderClass: "border-cyan-500/30",
      bgClass: "bg-cyan-500/15",
      textClass: "text-cyan-300",
    };
  }

  if (
    prov?.officialResourceConfirmed ||
    prov?.evidenceStage === "OFFICIAL_RESOURCE_CONFIRMED" ||
    rawStatus === "OFFICIAL_RESOURCE_CONFIRMED"
  ) {
    return {
      type: "OFFICIAL_RESOURCE_CONFIRMED",
      label: "OFFICIAL RESOURCE CONFIRMED",
      shortLabel: "Resource Confirmed",
      studentExplanation: `Official educational resource exists; current ${targetYear} applicability or full syllabus verification is not yet established.`,
      colorClass: "amber",
      borderClass: "border-amber-500/30",
      bgClass: "bg-amber-500/15",
      textClass: "text-amber-300",
    };
  }

  return {
    type: "SOURCE_REQUIRED",
    label: "SOURCE-REQUIRED",
    shortLabel: "Source Required",
    studentExplanation: `Official ${targetYear} confirmation required. Final board circular has not yet been published by the examination authority.`,
    colorClass: "amber",
    borderClass: "border-amber-500/30",
    bgClass: "bg-amber-500/15",
    textClass: "text-amber-300",
  };
}

export const CurriculumStatusBadge: React.FC<CurriculumStatusBadgeProps> = ({
  status,
  provenance,
  academicYear,
  sessionYear,
  examYear,
  sourceNote,
  subjectCode,
  conflicts,
  variant = "badge",
  showInspectButton = true,
  className = "",
}) => {
  const [isInspectOpen, setIsInspectOpen] = useState(false);

  const resolved = resolveStudentCurriculumState({
    status,
    provenance,
    academicYear,
  });

  const allConflicts =
    conflicts ||
    provenance?.unresolvedConflicts ||
    (provenance?.conflictDetails ? [provenance.conflictDetails] : []);

  const effectiveAcademicYear =
    academicYear || provenance?.academicYear || "2026-27";
  const effectiveSessionYear =
    sessionYear || provenance?.sessionYear || provenance?.resourceSessionYear;
  const effectiveExamYear =
    examYear || provenance?.examYear || provenance?.resourceExamYear;

  const renderIcon = () => {
    switch (resolved.type) {
      case "VERIFIED":
        return <ShieldCheck className="w-3.5 h-3.5 text-emerald-400 shrink-0" />;
      case "CURRICULUM_CONTENT_SUPPORTED":
        return <BookOpen className="w-3.5 h-3.5 text-cyan-400 shrink-0" />;
      case "OFFICIAL_RESOURCE_CONFIRMED":
        return <Info className="w-3.5 h-3.5 text-amber-400 shrink-0" />;
      case "APPLICATION_DERIVED":
        return <Sparkles className="w-3.5 h-3.5 text-purple-400 shrink-0" />;
      case "SOURCE_REQUIRED":
      default:
        return <ShieldAlert className="w-3.5 h-3.5 text-amber-400 shrink-0" />;
    }
  };

  return (
    <>
      {/* Badge / Pill View */}
      <div
        className={`inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-xs font-mono font-medium border transition-colors ${resolved.bgClass} ${resolved.borderClass} ${resolved.textClass} ${className}`}
        title={resolved.studentExplanation}
      >
        {renderIcon()}
        <span className="font-semibold tracking-wide">
          {variant === "compact" ? resolved.shortLabel : resolved.label}
        </span>
        {effectiveAcademicYear && (
          <span className="opacity-75 text-[10px]">({effectiveAcademicYear})</span>
        )}

        {showInspectButton && (
          <button
            type="button"
            onClick={(e) => {
              e.stopPropagation();
              setIsInspectOpen(true);
            }}
            className="ml-1 hover:text-white hover:opacity-100 transition-opacity focus:outline-none"
            aria-label="Inspect curriculum evidence and provenance"
            title="Inspect official source provenance"
          >
            <HelpCircle className="w-3 h-3" />
          </button>
        )}
      </div>

      {/* Inspect Provenance Modal */}
      {isInspectOpen && (
        <div
          role="dialog"
          aria-modal="true"
          aria-labelledby="curriculum-provenance-modal-title"
          className="fixed inset-0 z-50 flex items-center justify-center bg-black/75 backdrop-blur-sm p-4 animate-in fade-in duration-150"
          onClick={() => setIsInspectOpen(false)}
        >
          <div
            className="w-full max-w-xl max-h-[90vh] flex flex-col rounded-3xl bg-slate-900 border border-slate-700/80 shadow-2xl overflow-hidden animate-in zoom-in-95 duration-200"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Modal Header */}
            <div className="flex items-center justify-between p-5 border-b border-slate-800 bg-slate-950/60">
              <div className="flex items-center gap-2.5">
                <div
                  className={`w-9 h-9 rounded-xl flex items-center justify-center border ${resolved.bgClass} ${resolved.borderClass}`}
                >
                  {renderIcon()}
                </div>
                <div>
                  <h3
                    id="curriculum-provenance-modal-title"
                    className="text-base font-bold text-white font-heading"
                  >
                    Curriculum Evidence & Provenance
                  </h3>
                  <p className="text-xs text-slate-400">
                    Garia OS Provenance Registry • Academic Year {effectiveAcademicYear}
                  </p>
                </div>
              </div>

              <button
                type="button"
                onClick={() => setIsInspectOpen(false)}
                className="p-2 text-slate-400 hover:text-white rounded-xl hover:bg-slate-800 transition-colors"
                aria-label="Close inspection modal"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            {/* Modal Body */}
            <div className="flex-1 overflow-y-auto p-5 space-y-4 text-xs">
              {/* Evidence Status Callout */}
              <div
                className={`p-3.5 rounded-2xl border ${resolved.bgClass} ${resolved.borderClass} space-y-1.5`}
              >
                <div className="flex items-center justify-between">
                  <span className={`font-bold font-mono text-xs ${resolved.textClass}`}>
                    {resolved.label}
                  </span>
                  <span className="text-[11px] font-mono text-slate-400">
                    Academic Year {effectiveAcademicYear}
                  </span>
                </div>
                <p className="text-slate-200 leading-relaxed">
                  {resolved.studentExplanation}
                </p>
              </div>

              {/* Three-Tier Academic Calendar Distinction */}
              <div className="p-3.5 rounded-2xl bg-slate-950/70 border border-slate-800 space-y-2">
                <div className="flex items-center gap-2 text-slate-300 font-semibold">
                  <Calendar className="w-4 h-4 text-cyan-400" />
                  <span>Academic Session vs. Exam Year Tracking</span>
                </div>
                <div className="grid grid-cols-3 gap-2 pt-1 text-center font-mono">
                  <div className="p-2 rounded-xl bg-slate-900 border border-slate-800">
                    <div className="text-[10px] text-slate-400 uppercase">Academic Year</div>
                    <div className="text-xs font-bold text-cyan-300">
                      {effectiveAcademicYear}
                    </div>
                  </div>
                  <div className="p-2 rounded-xl bg-slate-900 border border-slate-800">
                    <div className="text-[10px] text-slate-400 uppercase">Session Year</div>
                    <div className="text-xs font-bold text-emerald-300">
                      {effectiveSessionYear || "Session 2025–27"}
                    </div>
                  </div>
                  <div className="p-2 rounded-xl bg-slate-900 border border-slate-800">
                    <div className="text-[10px] text-slate-400 uppercase">Target Exam Year</div>
                    <div className="text-xs font-bold text-amber-300">
                      {effectiveExamYear || "2027 (Class 12)"}
                    </div>
                  </div>
                </div>
                <p className="text-[11px] text-slate-400 leading-normal pt-1">
                  *Garia OS strictly prevents historical exam evidence (e.g., Annual Exam 2026)
                  from falsely verifying current academic year (2026–27 / Exam 2027) requirements.
                </p>
              </div>

              {/* Provenance Metadata Details */}
              {provenance ? (
                <div className="p-3.5 rounded-2xl bg-slate-950/70 border border-slate-800 space-y-2.5">
                  <div className="flex items-center gap-2 text-slate-300 font-semibold">
                    <FileText className="w-4 h-4 text-emerald-400" />
                    <span>Official Source Document Reference</span>
                  </div>

                  <div className="space-y-1.5 font-mono text-[11px]">
                    <div className="flex justify-between py-1 border-b border-slate-800/80">
                      <span className="text-slate-400">Authority:</span>
                      <span className="text-slate-200 font-bold">{provenance.authority}</span>
                    </div>
                    <div className="flex justify-between py-1 border-b border-slate-800/80">
                      <span className="text-slate-400">Document Title:</span>
                      <span className="text-slate-200 font-medium text-right max-w-[260px] truncate">
                        {provenance.documentTitle}
                      </span>
                    </div>
                    <div className="flex justify-between py-1 border-b border-slate-800/80">
                      <span className="text-slate-400">Document Type:</span>
                      <span className="text-slate-200">{provenance.documentType}</span>
                    </div>
                    {subjectCode && (
                      <div className="flex justify-between py-1 border-b border-slate-800/80">
                        <span className="text-slate-400">Official Subject Code:</span>
                        <span className="text-cyan-300 font-bold">{subjectCode}</span>
                      </div>
                    )}
                    {provenance.pageReference && (
                      <div className="flex justify-between py-1 border-b border-slate-800/80">
                        <span className="text-slate-400">Page / Question Ref:</span>
                        <span className="text-slate-300">{provenance.pageReference}</span>
                      </div>
                    )}
                    {provenance.publicationDate && (
                      <div className="flex justify-between py-1 border-b border-slate-800/80">
                        <span className="text-slate-400">Publication Date:</span>
                        <span className="text-slate-300">{provenance.publicationDate}</span>
                      </div>
                    )}
                    {provenance.sourceUrl && (
                      <div className="flex justify-between py-1 pt-2">
                        <span className="text-slate-400">Source Link:</span>
                        <a
                          href={provenance.sourceUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="text-cyan-400 hover:underline flex items-center gap-1 font-semibold"
                        >
                          <span>Official Portal</span>
                          <ExternalLink className="w-3 h-3" />
                        </a>
                      </div>
                    )}
                  </div>
                </div>
              ) : (
                <div className="p-3.5 rounded-2xl bg-slate-950/70 border border-slate-800 space-y-1.5">
                  <div className="flex items-center gap-2 text-slate-300 font-semibold">
                    <Info className="w-4 h-4 text-cyan-400" />
                    <span>Provenance Registration Notice</span>
                  </div>
                  <p className="text-slate-300 text-xs leading-relaxed">
                    {sourceNote ||
                      "This curriculum item is currently in SOURCE-REQUIRED status awaiting the formal release and ingestion of the official circular."}
                  </p>
                </div>
              )}

              {/* Unresolved Conflicts Section (if any) */}
              {allConflicts.length > 0 && (
                <div className="p-3.5 rounded-2xl bg-amber-950/20 border border-amber-500/30 space-y-2">
                  <div className="flex items-center gap-2 text-amber-300 font-semibold">
                    <AlertTriangle className="w-4 h-4 text-amber-400" />
                    <span>Officially Cataloged Curriculum Conflicts ({allConflicts.length})</span>
                  </div>
                  <div className="space-y-2">
                    {allConflicts.map((conf, idx) => (
                      <div
                        key={idx}
                        className="p-2.5 rounded-xl bg-slate-900/80 border border-amber-500/20 text-xs space-y-1"
                      >
                        <div className="flex items-center justify-between">
                          <span className="font-mono text-[10px] font-bold text-amber-300">
                            {conf.category || "CURRICULUM_CONFLICT"}
                          </span>
                          <span className="text-[10px] text-slate-400 font-mono">
                            {conf.conflictStatus || "UNRESOLVED_PENDING_2026_27_CIRCULAR"}
                          </span>
                        </div>
                        <p className="text-slate-300 leading-snug">
                          {conf.conflictDescription}
                        </p>
                        <div className="text-[11px] text-amber-200/90 pt-0.5">
                          <span className="font-semibold text-amber-300">Resolution Action: </span>
                          {conf.recommendedReviewAction}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Application-Derived Disclosure */}
              <div className="p-3 rounded-xl bg-slate-950/40 border border-slate-800 text-[11px] text-slate-400 leading-relaxed">
                <span className="font-semibold text-slate-300">Garia OS Anti-Hallucination Policy: </span>
                Curriculum data is never converted into VERIFIED status through inference, historical assumptions, or AI generation. All learning recommendations are labeled as Application-Derived.
              </div>
            </div>

            {/* Modal Footer */}
            <div className="p-4 border-t border-slate-800 bg-slate-950/80 flex items-center justify-end">
              <button
                type="button"
                onClick={() => setIsInspectOpen(false)}
                className="px-4 py-2 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-medium text-xs transition-colors"
              >
                Close Audit View
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
};
