import React, { useState, useMemo } from "react";
import { motion, AnimatePresence } from "motion/react";
import {
  X,
  Search,
  ShieldAlert,
  Calendar,
  Clock,
  Target,
  Sparkles,
  BookOpen,
  BarChart2,
  AlertTriangle,
  Award,
  Bell,
  ChevronRight,
  TrendingUp,
  FileCheck2,
  Zap,
} from "lucide-react";
import { AppLanguage, translations } from "../utils/i18n";

export type ExamDrawerAction =
  // Exam Dashboard
  | "dashboard_upcoming"
  | "dashboard_countdown"
  | "dashboard_calendar"
  // Study Planning
  | "planning_smart_planner"
  | "planning_revision_planner"
  | "planning_daily_targets"
  // Performance
  | "performance_mock_analytics"
  | "performance_subject_perf"
  | "performance_weak_areas"
  // Intelligence
  | "intel_vvi_predictions"
  | "intel_high_yield"
  | "intel_exam_alerts";

interface ExamIntelligenceDrawerProps {
  isOpen: boolean;
  onClose: () => void;
  onSelectAction: (action: ExamDrawerAction) => void;
  activeAction?: ExamDrawerAction | string;
  currentLanguage?: AppLanguage;
  studentClassName?: string;
  studentStream?: string;
  examReadinessScore?: number;
}

export const ExamIntelligenceDrawer: React.FC<ExamIntelligenceDrawerProps> = ({
  isOpen,
  onClose,
  onSelectAction,
  activeAction = "dashboard_upcoming",
  currentLanguage = "en",
  studentClassName = "Class 10",
  studentStream = "Science",
  examReadinessScore = 78,
}) => {
  const [searchQuery, setSearchQuery] = useState("");
  const t = translations[currentLanguage] || translations.en;

  const drawerItems = useMemo(
    () => [
      // Exam Dashboard
      {
        id: "dashboard_upcoming" as ExamDrawerAction,
        section: "dashboard",
        label: "Upcoming Exams",
        desc: "Active board exam timeline, admit card schedules & date sheets",
        icon: Calendar,
        badge: "Timeline",
        color: "from-blue-400 to-indigo-500",
      },
      {
        id: "dashboard_countdown" as ExamDrawerAction,
        section: "dashboard",
        label: "Exam Countdown",
        desc: "Live days/hours/minutes countdown till official exam papers",
        icon: Clock,
        badge: "Live Clock",
        color: "from-indigo-400 to-purple-500",
      },
      {
        id: "dashboard_calendar" as ExamDrawerAction,
        section: "dashboard",
        label: "Exam Calendar",
        desc: "Unified monthly calendar with test schedules, pre-boards & revision slots",
        icon: Calendar,
        color: "from-cyan-400 to-blue-500",
      },

      // Study Planning
      {
        id: "planning_smart_planner" as ExamDrawerAction,
        section: "planning",
        label: "Smart Study Planner",
        desc: "Dynamic chapter weighting daily study routine generated by Abya AI",
        icon: Sparkles,
        badge: "AI Plan",
        color: "from-emerald-400 to-teal-500",
      },
      {
        id: "planning_revision_planner" as ExamDrawerAction,
        section: "planning",
        label: "Revision Planner",
        desc: "Spaced repetition (1-3-7-15-30 days) review queue for high-yield topics",
        icon: Target,
        badge: "Spaced",
        color: "from-teal-400 to-cyan-500",
      },
      {
        id: "planning_daily_targets" as ExamDrawerAction,
        section: "planning",
        label: "Daily Targets",
        desc: "Custom syllabus targets, practice quota & chapter milestone tracker",
        icon: Target,
        color: "from-blue-400 to-cyan-500",
      },

      // Performance
      {
        id: "performance_mock_analytics" as ExamDrawerAction,
        section: "performance",
        label: "Mock Test Analytics",
        desc: "Score distribution, percentile trends, accuracy & speed breakdown",
        icon: Award,
        badge: "Analytics",
        color: "from-purple-400 to-pink-500",
      },
      {
        id: "performance_subject_perf" as ExamDrawerAction,
        section: "performance",
        label: "Subject Performance",
        desc: "Subject-wise readiness ratings, strongest chapters & test histories",
        icon: BarChart2,
        color: "from-pink-400 to-rose-500",
      },
      {
        id: "performance_weak_areas" as ExamDrawerAction,
        section: "performance",
        label: "Weak Areas",
        desc: "High priority risk chapters requiring immediate revision intervention",
        icon: AlertTriangle,
        badge: "Critical",
        color: "from-rose-400 to-red-500",
      },

      // Intelligence
      {
        id: "intel_vvi_predictions" as ExamDrawerAction,
        section: "intelligence",
        label: "VVI Predictions",
        desc: "High probability questions & core theorem predictions for 2026/2027 boards",
        icon: Zap,
        badge: "Predictions",
        color: "from-amber-400 to-orange-500",
      },
      {
        id: "intel_high_yield" as ExamDrawerAction,
        section: "intelligence",
        label: "High Yield Topics",
        desc: "80/20 Pareto principle topics responsible for 70%+ of total exam marks",
        icon: Sparkles,
        badge: "80/20 Rule",
        color: "from-amber-400 to-yellow-500",
      },
      {
        id: "intel_exam_alerts" as ExamDrawerAction,
        section: "intelligence",
        label: "Exam Alerts & Bulletins",
        desc: "Official board circulars, sample paper releases & marking scheme updates",
        icon: Bell,
        color: "from-teal-400 to-emerald-500",
      },
    ],
    []
  );

  const filteredItems = useMemo(() => {
    if (!searchQuery.trim()) return drawerItems;
    const q = searchQuery.toLowerCase();
    return drawerItems.filter(
      (item) =>
        item.label.toLowerCase().includes(q) ||
        item.desc.toLowerCase().includes(q)
    );
  }, [drawerItems, searchQuery]);

  const sections = [
    {
      id: "dashboard",
      title: "Exam Dashboard",
      items: filteredItems.filter((i) => i.section === "dashboard"),
    },
    {
      id: "planning",
      title: "Study Planning",
      items: filteredItems.filter((i) => i.section === "planning"),
    },
    {
      id: "performance",
      title: "Performance",
      items: filteredItems.filter((i) => i.section === "performance"),
    },
    {
      id: "intelligence",
      title: "Intelligence",
      items: filteredItems.filter((i) => i.section === "intelligence"),
    },
  ].filter((s) => s.items.length > 0);

  return (
    <AnimatePresence>
      {isOpen && (
        <div
          id="exam-drawer-overlay"
          className="fixed inset-0 z-50 flex justify-end bg-black/70 backdrop-blur-md"
          onClick={onClose}
        >
          <motion.div
            id="exam-drawer-panel"
            initial={{ x: "100%", opacity: 0.5 }}
            animate={{ x: 0, opacity: 1 }}
            exit={{ x: "100%", opacity: 0 }}
            transition={{ type: "spring", damping: 26, stiffness: 280 }}
            onClick={(e) => e.stopPropagation()}
            className="w-full max-w-md h-full bg-slate-950/95 border-l border-white/15 shadow-2xl flex flex-col overflow-hidden text-white"
          >
            {/* Header */}
            <div className="p-4 border-b border-white/10 space-y-3 shrink-0 bg-slate-900/60 backdrop-blur-xl">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2.5">
                  <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-blue-400 to-indigo-500 p-0.5 flex items-center justify-center text-slate-950 font-bold shadow-md">
                    <ShieldAlert className="w-5 h-5 text-slate-950" />
                  </div>
                  <div>
                    <h3 className="font-bold text-base font-heading text-white flex items-center gap-2">
                      <span>Exam Intelligence Drawer</span>
                      <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-blue-500/15 text-blue-400 border border-blue-500/30">
                        {examReadinessScore}% Ready
                      </span>
                    </h3>
                    <p className="text-xs text-slate-400">
                      {studentClassName} • {studentStream} Strategic Hub
                    </p>
                  </div>
                </div>

                <button
                  id="close-exam-drawer-btn"
                  onClick={onClose}
                  aria-label="Close Exam Intelligence Drawer"
                  className="w-10 h-10 rounded-full bg-white/5 hover:bg-white/10 border border-white/10 flex items-center justify-center text-slate-400 hover:text-white transition-colors"
                >
                  <X className="w-5 h-5" />
                </button>
              </div>

              {/* Search */}
              <div className="relative">
                <Search className="w-4 h-4 text-slate-400 absolute left-3.5 top-1/2 -translate-y-1/2" />
                <input
                  id="exam-drawer-search"
                  type="text"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  placeholder="Search Countdown, Planners, Weak Areas, VVI..."
                  className="w-full bg-slate-900/90 border border-white/10 rounded-2xl pl-10 pr-9 py-2.5 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-blue-500/50 transition-colors"
                />
                {searchQuery && (
                  <button
                    onClick={() => setSearchQuery("")}
                    className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-white text-xs p-1"
                  >
                    <X className="w-3.5 h-3.5" />
                  </button>
                )}
              </div>
            </div>

            {/* List */}
            <div className="flex-1 overflow-y-auto p-4 space-y-5 scrollbar-thin scrollbar-thumb-white/10">
              {sections.map((sec) => (
                <div key={sec.id} className="space-y-2">
                  <h4 className="text-[11px] font-bold uppercase tracking-wider text-slate-400 font-mono flex items-center justify-between px-1">
                    <span>{sec.title}</span>
                    <span className="text-[10px] text-slate-500 font-normal">
                      {sec.items.length} items
                    </span>
                  </h4>

                  <div className="grid grid-cols-1 gap-2">
                    {sec.items.map((item) => {
                      const Icon = item.icon;
                      const isActive = activeAction === item.id;

                      return (
                        <button
                          key={item.id}
                          onClick={() => {
                            onSelectAction(item.id);
                            onClose();
                          }}
                          className={`w-full min-h-[48px] p-3 rounded-2xl border transition-all text-left flex items-center justify-between gap-3 group active:scale-[0.99] ${
                            isActive
                              ? "bg-gradient-to-r from-blue-500/20 to-indigo-500/10 border-blue-500/40 shadow-sm"
                              : "bg-slate-900/60 hover:bg-slate-900/90 border-white/10 hover:border-white/20"
                          }`}
                        >
                          <div className="flex items-center gap-3 min-w-0">
                            <div
                              className={`w-9 h-9 rounded-xl bg-gradient-to-tr ${item.color} p-0.5 flex items-center justify-center text-slate-950 font-bold shadow-md shrink-0 group-hover:scale-105 transition-transform`}
                            >
                              <Icon className="w-4 h-4 text-white" />
                            </div>
                            <div className="min-w-0">
                              <div className="flex items-center gap-2">
                                <span className="font-bold text-xs text-white group-hover:text-blue-300 transition-colors truncate">
                                  {item.label}
                                </span>
                                {item.badge && (
                                  <span className="text-[9px] font-mono font-bold px-1.5 py-0.2 rounded-full bg-blue-500/20 text-blue-300 border border-blue-500/30 shrink-0">
                                    {item.badge}
                                  </span>
                                )}
                              </div>
                              <p className="text-[11px] text-slate-400 truncate mt-0.5">
                                {item.desc}
                              </p>
                            </div>
                          </div>

                          <ChevronRight className="w-4 h-4 text-slate-500 group-hover:text-blue-400 group-hover:translate-x-0.5 transition-all shrink-0" />
                        </button>
                      );
                    })}
                  </div>
                </div>
              ))}

              {filteredItems.length === 0 && (
                <div className="p-8 text-center space-y-2">
                  <p className="text-sm font-bold text-slate-300">
                    No exam items match "{searchQuery}"
                  </p>
                  <p className="text-xs text-slate-500">
                    Try searching for Countdown, Weak Areas, or VVI Predictions.
                  </p>
                </div>
              )}
            </div>

            {/* Footer */}
            <div className="p-3 border-t border-white/10 bg-slate-900/80 backdrop-blur-xl flex items-center justify-between text-xs text-slate-400 font-mono shrink-0">
              <span className="flex items-center gap-1.5 text-blue-400">
                <span className="w-2 h-2 rounded-full bg-blue-400 animate-pulse" />
                Exam Intelligence Drawer Active
              </span>
              <span>1-Tap Strategy</span>
            </div>
          </motion.div>
        </div>
      )}
    </AnimatePresence>
  );
};
