plugins {
    id 'com.android.application'
}

android {
    namespace 'com.gariaos.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.gariaos.app"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.6.0"

        manifestPlaceholders = [
            hostName: "ais-pre-v7vcv6eevdr5eg5w3uyx6h-727347822999.asia-southeast1.run.app",
            defaultUrl: "https://ais-pre-v7vcv6eevdr5eg5w3uyx6h-727347822999.asia-southeast1.run.app/",
            launcherName: "Garia OS",
            assetStatements: '[]'
        ]
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.android.browserhelper:androidbrowserhelper:2.5.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.browser:browser:1.8.0'
}

